- name: Instala o agente para o Debian
  apt: 
    name: puppet-agent
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Instala o agente para o RedHat
  yum:    
    name: puppet-agent
    state: present
  when: ansible_os_family == 'RedHat'

- name: Inicia o puppet-agent
  service:
    name: puppet
    state: started
    enabled: yes
